version: '3.8'
services:
  php:
    build: .
    ports:
      - "8000:8000" # Map container's port 8000 to localhost's port 8000
    volumes:
      - .:/app # Sync local project files with the container for development
